global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus-service-demo'
    static_configs:
      - targets: ['prometheus-service-demo-0:8080', 'prometheus-service-demo-1:8080', 'prometheus-service-demo-2:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
