{
 "title": "Monitoreo API",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Percentil 90 de Tiempo de Respuesta HTTP",
   "type": "timeseries",
   "description": "Por route, method y status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le, route, method, status)(rate(demo_api_request_duration_seconds_bucket[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentil 95 de Tiempo de Respuesta HTTP",
   "type": "timeseries",
   "description": "Por route y method",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, route, method)(rate(demo_api_request_duration_seconds_bucket[5m])))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duración Promedio de Respuestas HTTP",
   "type": "timeseries",
   "description": "Por route y method",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (route, method)(rate(demo_api_request_duration_seconds_sum[5m]))\n/\nsum by (route, method)(rate(demo_api_request_duration_seconds_count[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}